FROM php:8.1.3-fpm-alpine3.15


ARG EXTRA_MONGODB_ENABLE=true
ARG EXTRA_MSGPACK_ENABLE=true
ARG EXTRA_PROTOBUF_ENABLE=true
ARG EXTRA_PSR_ENABLE=true
ARG EXTRA_REDIS_ENABLE=true
ARG EXTRA_SWOOLE_ENABLE=true
ARG EXTRA_UUID_ENABLE=true
ARG EXTRA_YAML_ENABLE=true
ARG EXTRA_ZEPHIR_ENABLE=true
ARG EXTRA_COMPOSER_ENABLE=true

RUN \
    # 替换 apk 源
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update --no-cache && apk upgrade --no-cache && apk add --no-cache \
        argon2-libs \
        brotli-libs \
        c-client \
        curl \
        gdbm \
        gettext-libs \
        icu-libs \
        imagemagick \
        imagemagick-libs \
        libbz2 \
        libedit \
        libevent \
        libffi \
        libgcrypt \
        libgd \
        libgomp \
        libgpg-error \
        libldap \
        liblzf \
        libmcrypt \
        libpq \
        libsasl \
        libstdc++ \
        libxml2 \
        libxslt \
        libzip \
        lz4-libs \
        net-snmp-libs \
        pcre \
        pcre2 \
        protoc \
        rabbitmq-c \
        snappy \
        tidyhtml-libs \
        xz-libs \
        yaml \
        zstd-libs && \
    # 编译环境
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
        argon2-dev \
        brotli-dev \
        build-base \
        bzip2-dev \
        curl-dev \
        gd-dev \
        gdbm-dev \
        gettext-dev \
        git \
        icu-dev \
        imagemagick-dev \
        imap-dev \
        libedit-dev \
        libffi-dev \
        libgcrypt-dev \
        liblzf-dev \
        libmcrypt-dev \
        libpq-dev \
        libxml2-dev \
        libxslt-dev \
        libzip-dev \
        lz4-dev \
        mysql-dev \
        net-snmp-dev \
        openldap-dev \
        pcre-dev \
        pcre2-dev \
        rabbitmq-c-dev \
        snappy-dev \
        tidyhtml-dev \
        tzdata \
        yaml-dev \
        zlib-dev && \
    # 安装 PHP 扩展
    # inotify
    curl -sfL https://github.com/arnaud-lb/php-inotify/archive/refs/tags/${INOTIFY}.tar.gz -o /tmp/inotify.tar.gz && \
    mkdir /usr/src/php/ext/inotify && tar xfz /tmp/inotify.tar.gz --strip-components=1 -C /usr/src/php/ext/inotify && \
    docker-php-ext-configure inotify && \
    docker-php-ext-install -j$(nproc) --ini-name 40_inotify.ini inotify && \
    # lzf
    curl -sfL https://github.com/php/pecl-file_formats-lzf/archive/refs/tags/LZF-${LZF}.tar.gz -o /tmp/lzf.tar.gz && \
    mkdir /usr/src/php/ext/lzf && tar xfz /tmp/lzf.tar.gz --strip-components=1 -C /usr/src/php/ext/lzf && \
    docker-php-ext-configure lzf && \
    docker-php-ext-install -j$(nproc) --ini-name 50_lzf.ini lzf && \
    # mongodb
    git clone -q -b ${MONGODB} --depth 1 https://github.com/mongodb/mongo-php-driver.git /usr/src/php/ext/mongodb && \
    cd /usr/src/php/ext/mongodb && git submodule update --init && \
    docker-php-ext-configure mongodb && \
    docker-php-ext-install -j$(nproc) --ini-name 40_mongodb.ini mongodb && \
    # msgpack
    curl -sfL https://github.com/msgpack/msgpack-php/archive/refs/tags/msgpack-${MSGPACK}.tar.gz -o /tmp/msgpack.tar.gz && \
    mkdir /usr/src/php/ext/msgpack && tar xfz /tmp/msgpack.tar.gz --strip-components=1 -C /usr/src/php/ext/msgpack && \
    docker-php-ext-configure msgpack && \
    docker-php-ext-install -j$(nproc) --ini-name 10_msgpack.ini msgpack && \
    # mcrypt
    curl -sfL https://github.com/php/pecl-encryption-mcrypt/archive/refs/tags/${MCRYPT}.tar.gz -o /tmp/mcrypt.tar.gz && \
    mkdir /usr/src/php/ext/mcrypt && tar xfz /tmp/mcrypt.tar.gz --strip-components=1 -C /usr/src/php/ext/mcrypt && \
    docker-php-ext-configure mcrypt && \
    docker-php-ext-install -j$(nproc) --ini-name 10_mcrypt.ini mcrypt && \
    # protobuf
    curl -sfL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF}/protobuf-php-${PROTOBUF}.tar.gz -o /tmp/protobuf.tar.gz && \
    mkdir /tmp/protobuf && tar xfz /tmp/protobuf.tar.gz --strip-components=1 -C /tmp/protobuf && \
    mv /tmp/protobuf/php/ext/google/protobuf /usr/src/php/ext/ && \
    docker-php-ext-configure protobuf && \
    docker-php-ext-install -j$(nproc) --ini-name 10_protobuf.ini protobuf && \
    # psr
    curl -sfL https://github.com/jbboehr/php-psr/archive/refs/tags/v${PSR}.tar.gz -o /tmp/psr.tar.gz && \
    mkdir /usr/src/php/ext/psr && tar xfz /tmp/psr.tar.gz --strip-components=1 -C /usr/src/php/ext/psr && \
    docker-php-ext-configure psr && \
    docker-php-ext-install -j$(nproc) --ini-name 10_psr.ini psr && \
    # lz4
    curl -sfL https://github.com/kjdev/php-ext-lz4/archive/refs/tags/${LZ4}.tar.gz -o /tmp/lz4.tar.gz && \
    mkdir /usr/src/php/ext/lz4 && tar xfz /tmp/lz4.tar.gz --strip-components=1 -C /usr/src/php/ext/lz4 && \
    docker-php-ext-configure lz4 --with-lz4-includedir=/usr && \
    docker-php-ext-install -j$(nproc) --ini-name 10_lz4.ini lz4 && \
    # redis
    curl -sfL https://github.com/phpredis/phpredis/archive/refs/tags/${REDIS}.tar.gz -o /tmp/redis.tar.gz && \
    mkdir /usr/src/php/ext/redis && tar xfz /tmp/redis.tar.gz --strip-components=1 -C /usr/src/php/ext/redis && \
    docker-php-ext-configure redis \
        --enable-redis-igbinary --enable-redis-msgpack \
        --enable-redis-lzf --with-liblzf=/usr --enable-redis-zstd --enable-redis-lz4 --with-liblz4=/usr && \
    docker-php-ext-install -j$(nproc) --ini-name 40_redis.ini redis && \
    # uuid
    curl -sfL https://github.com/php/pecl-networking-uuid/archive/refs/tags/uuid-${UUID}.tar.gz -o /tmp/uuid.tar.gz && \
    mkdir /usr/src/php/ext/uuid && tar xfz /tmp/uuid.tar.gz --strip-components=1 -C /usr/src/php/ext/uuid && \
    docker-php-ext-configure uuid && \
    docker-php-ext-install -j$(nproc) --ini-name 10_uuid.ini uuid && \
    # yaml
    curl -sfL https://github.com/php/pecl-file_formats-yaml/archive/refs/tags/${YAML}.tar.gz -o /tmp/yaml.tar.gz && \
    mkdir /usr/src/php/ext/yaml && tar xfz /tmp/yaml.tar.gz --strip-components=1 -C /usr/src/php/ext/yaml && \
    docker-php-ext-configure yaml && \
    docker-php-ext-install -j$(nproc) --ini-name 10_yaml.ini yaml && \
    # csv
    curl -sfL https://gitlab.com/Girgias/csv-php-extension/-/archive/${CSV}/csv-php-extension-${CSV}.tar.gz -o /tmp/csv.tar.gz && \
    mkdir /usr/src/php/ext/csv && tar xfz /tmp/csv.tar.gz --strip-components=1 -C /usr/src/php/ext/csv && \
    docker-php-ext-configure csv && \
    docker-php-ext-install -j$(nproc) --ini-name 10_csv.ini csv && \
    # zephir-parser
    curl -sfL https://github.com/zephir-lang/php-zephir-parser/archive/refs/tags/v${ZEPHIR}.tar.gz -o /tmp/zephir.tar.gz && \
    mkdir /usr/src/php/ext/zephir && tar xfz /tmp/zephir.tar.gz --strip-components=1 -C /usr/src/php/ext/zephir && \
    docker-php-ext-configure zephir && \
    docker-php-ext-install -j$(nproc) --ini-name 90_zephir.ini zephir && \
    # snappy
    curl -sfL https://github.com/kjdev/php-ext-snappy/archive/refs/tags/0.2.1.tar.gz -o /tmp/snappy.tar.gz && \
    mkdir /usr/src/php/ext/snappy && tar xfz /tmp/snappy.tar.gz --strip-components=1 -C /usr/src/php/ext/snappy && \
    docker-php-ext-configure snappy --with-snappy-includedir=/usr && \
    docker-php-ext-install -j$(nproc) --ini-name 10_snappy.ini snappy && \
    # 启用已安装 PHP 扩展
    rm -f /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini && \
    docker-php-ext-enable --ini-name 00_sodium.ini sodium && \
    docker-php-ext-enable --ini-name 00_opcache.ini opcache && \
    # 安装 OpenRC
    apk add --no-cache openrc bash vim && \
    # Disable getty's
    sed -i 's/^\(tty\d\:\:\)/#\1/g' /etc/inittab && \
    # Change rc.conf
    sed -i \
        # Change subsystem type to "docker"
        -e 's/#rc_sys=".*"/rc_sys="docker"/g' \
        # Allow all variables through
        -e 's/#rc_env_allow=".*"/rc_env_allow="\*"/g' \
        # Start crashed services
        -e 's/#rc_crashed_stop=.*/rc_crashed_stop=NO/g' \
        -e 's/#rc_crashed_start=.*/rc_crashed_start=YES/g' \
        # Define extra dependencies for services
        -e 's/#rc_provide=".*"/rc_provide="loopback net"/g' \
        /etc/rc.conf && \
    # Remove unnecessary services
    rm -f /etc/init.d/hwdrivers /etc/init.d/hwclock /etc/init.d/hwdrivers /etc/init.d/modules \
        /etc/init.d/modules-load /etc/init.d/modloop /etc/init.d/machine-id && \
    # Don't do cgroups
    sed -i 's/\tcgroup_add_service/\t#cgroup_add_service/g' /lib/rc/sh/openrc-run.sh && \
    sed -i 's/VSERVER/DOCKER/Ig' /lib/rc/sh/init.sh && \
    # 修改时区
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone && \
    # 修改 bash 环境配置
    echo "PS1='\033[1;33m\h \033[1;34m[\w] \033[1;35m\D{%D %T}\n\[\033[1;36m\]\u@\l \[\033[00m\]\$ '" > /root/.bashrc && \
    echo "alias ll='ls -l'" >> /root/.bashrc && \
    # 清理构建过程临时文件
    docker-php-source delete && apk del .build-deps && rm -rf /tmp/* && \
    # 链接常用路径
    ln -s /usr/local/bin/php /usr/bin/ && ln -s /usr/local/etc/php /etc/ && ln -s /usr/local/etc/php-fpm.d /etc/ && \
    # Composer
    curl -sfL https://getcomposer.org/download/${COMPOSER}/composer.phar -o /usr/bin/composer && \
    chmod +x /usr/bin/composer && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

CMD ["/sbin/init"]
