version: "3.9"

services:
    7.4-fpm:
        image: fooz79/php-with-ext:7.4-fpm
        build:
            dockerfile: Dockerfile
            args:
                PHP_MAJOR: "7.4"
                PHP_MINOR: "28"
                RUNMODE: fpm
    7.4-cli:
        image: fooz79/php-with-ext:7.4-cli
        build:
            dockerfile: Dockerfile
            args:
                PHP_MAJOR: "7.4"
                PHP_MINOR: "28"
                RUNMODE: cli
    8.0-fpm:
        image: fooz79/php-with-ext:8.0-fpm
        build:
            dockerfile: Dockerfile
            args:
                PHP_MAJOR: "8.0"
                PHP_MINOR: "16"
                RUNMODE: fpm
    8.0-cli:
        image: fooz79/php-with-ext:8.0-cli
        build:
            dockerfile: Dockerfile
            args:
                PHP_MAJOR: "8.0"
                PHP_MINOR: "16"
                RUNMODE: cli
    8.1-fpm:
        image: fooz79/php-with-ext:8.1-fpm
        build:
            dockerfile: Dockerfile
            args:
                PHP_MAJOR: "8.1"
                PHP_MINOR: "3"
                RUNMODE: fpm
    8.1-cli:
        image: fooz79/php-with-ext:8.1-cli
        build:
            dockerfile: Dockerfile
            args:
                PHP_MAJOR: "8.1"
                PHP_MINOR: "3"
                RUNMODE: cli
