FROM php:8.1.3-fpm-alpine3.15


ARG EXTRA_MONGODB_ENABLE=true
ARG EXTRA_MSGPACK_ENABLE=true
ARG EXTRA_PROTOBUF_ENABLE=true
ARG EXTRA_PSR_ENABLE=true
ARG EXTRA_REDIS_ENABLE=true
ARG EXTRA_SWOOLE_ENABLE=true
ARG EXTRA_UUID_ENABLE=true
ARG EXTRA_YAML_ENABLE=true
ARG EXTRA_ZEPHIR_ENABLE=true
ARG EXTRA_COMPOSER_ENABLE=true

RUN \
    # 替换 apk 源
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk update --no-cache && apk upgrade --no-cache && apk add --no-cache \
        argon2-libs \
        brotli-libs \
        c-client \
        curl \
        gdbm \
        gettext-libs \
        icu-libs \
        imagemagick \
        imagemagick-libs \
        libbz2 \
        libedit \
        libevent \
        libffi \
        libgcrypt \
        libgd \
        libgomp \
        libgpg-error \
        libldap \
        liblzf \
        libmcrypt \
        libpq \
        libsasl \
        libstdc++ \
        libxml2 \
        libxslt \
        libzip \
        lz4-libs \
        net-snmp-libs \
        pcre \
        pcre2 \
        protoc \
        rabbitmq-c \
        snappy \
        tidyhtml-libs \
        xz-libs \
        yaml \
        zstd-libs && \
    # 编译环境
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
        argon2-dev \
        brotli-dev \
        build-base \
        bzip2-dev \
        curl-dev \
        gd-dev \
        gdbm-dev \
        gettext-dev \
        git \
        icu-dev \
        imagemagick-dev \
        imap-dev \
        libedit-dev \
        libffi-dev \
        libgcrypt-dev \
        liblzf-dev \
        libmcrypt-dev \
        libpq-dev \
        libxml2-dev \
        libxslt-dev \
        libzip-dev \
        lz4-dev \
        mysql-dev \
        net-snmp-dev \
        openldap-dev \
        pcre-dev \
        pcre2-dev \
        rabbitmq-c-dev \
        snappy-dev \
        tidyhtml-dev \
        tzdata \
        yaml-dev \
        zlib-dev && \
    # 安装 PHP 扩展
    # 启用已安装 PHP 扩展
    rm -f /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini && \
    docker-php-ext-enable --ini-name 00_sodium.ini sodium && \
    docker-php-ext-enable --ini-name 00_opcache.ini opcache && \
    # 安装 OpenRC
    apk add --no-cache openrc bash vim && \
    # Disable getty's
    sed -i 's/^\(tty\d\:\:\)/#\1/g' /etc/inittab && \
    # Change rc.conf
    sed -i \
        # Change subsystem type to "docker"
        -e 's/#rc_sys=".*"/rc_sys="docker"/g' \
        # Allow all variables through
        -e 's/#rc_env_allow=".*"/rc_env_allow="\*"/g' \
        # Start crashed services
        -e 's/#rc_crashed_stop=.*/rc_crashed_stop=NO/g' \
        -e 's/#rc_crashed_start=.*/rc_crashed_start=YES/g' \
        # Define extra dependencies for services
        -e 's/#rc_provide=".*"/rc_provide="loopback net"/g' \
        /etc/rc.conf && \
    # Remove unnecessary services
    rm -f /etc/init.d/hwdrivers /etc/init.d/hwclock /etc/init.d/hwdrivers /etc/init.d/modules \
        /etc/init.d/modules-load /etc/init.d/modloop /etc/init.d/machine-id && \
    # Don't do cgroups
    sed -i 's/\tcgroup_add_service/\t#cgroup_add_service/g' /lib/rc/sh/openrc-run.sh && \
    sed -i 's/VSERVER/DOCKER/Ig' /lib/rc/sh/init.sh && \
    # 修改时区
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone && \
    # 修改 bash 环境配置
    echo "PS1='\033[1;33m\h \033[1;34m[\w] \033[1;35m\D{%D %T}\n\[\033[1;36m\]\u@\l \[\033[00m\]\$ '" > /root/.bashrc && \
    echo "alias ll='ls -l'" >> /root/.bashrc && \
    # 清理构建过程临时文件
    docker-php-source delete && apk del .build-deps && rm -rf /tmp/* && \
    # 链接常用路径
    ln -s /usr/local/bin/php /usr/bin/ && ln -s /usr/local/etc/php /etc/ && ln -s /usr/local/etc/php-fpm.d /etc/ && \
    # Composer
    curl -sfL https://getcomposer.org/download/${COMPOSER}/composer.phar -o /usr/bin/composer && \
    chmod +x /usr/bin/composer && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

CMD ["/sbin/init"]
