name: build and release

on:
    push:
        branches: [action]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker build -f Dockerfile.dev --no-cache --compress -t fooz79/php-with-ext:demo
